Adds option to recursively checkout submodules
denolehov/obsidian-git pull request #409
Opened 2022-12-27 14:05 UTC by DenEwout

This commit allows users to automatically checkout the same branch in submodules (if present) as the root repository. This does not create any branches.

(co-authored by @yentlprojects)

2022-12-28 16:31 UTC, Vinzent03 commented on src/types.ts
> +	matchRootBranchName: boolean;
I think this setting is a left over?

2022-12-29 09:05 UTC, DenEwout commented on src/types.ts
> +	matchRootBranchName: boolean;
Yup! Removed it, cheers.

2023-01-04 17:00 UTC, Vinzent03 requested changes

2023-01-04 17:00 UTC, Vinzent03 commented on src/simpleGit.ts
> +            if (this.plugin.settings.submoduleRecurseCheckout) {
I think this check is wrong here, because the previous commit won't work with this settings disabled, doesn't it?

2023-01-04 17:01 UTC, Vinzent03 commented
I've fixed the `.editorconfig` file now. I'm using everywhere `space` now.

2023-01-06 21:11 UTC, merged

2023-01-06 21:11 UTC, Vinzent03 commented
LGTM!