Fix CI errors
denolehov/obsidian-git pull request #602
Opened 2023-09-10 14:24 UTC by tamiroh

2023-09-10 14:31 UTC, tamiroh commented on .eslintrc
> +                "no-undef": "off" // TODO: remove this line
Here I temporarily suppressing the `no-undef` errors, which currently occurs for global objects such as `window`, `app` and so on. I can't solve this problem right now, so this is a temporary work around.

2023-09-10 14:35 UTC, tamiroh commented on src/ui/sourceControl/components/stagedFileComponent.svelte
> -    $: formattedPath = change.vault_path;
I removed this line to suppress the following error.

```
14:8   error  'formattedPath' is defined but never used  @typescript-eslint/no-unused-vars
```

This variable is not actually referenced and should not affect the behavior.

2023-09-11 10:40 UTC, Vinzent03 requested changes

2023-09-11 10:40 UTC, Vinzent03 commented on src/main.ts
> +                    (leaf.view.file as any).path == file.path
```suggestion
                    leaf.view.file?.path == file.path
```

2023-09-11 11:01 UTC, Vinzent03 commented
Thanks for the fixes!

2023-09-11 11:01 UTC, merged